'''
Dicionário para associação tabela de variaveis <--> software
'''
io = {}
io['EXP 00 – ED 01'] = '1'
io['EXP 00 – ED 02'] = '2'
io['EXP 00 – ED 03'] = '3'
io['EXP 00 – ED 04'] = '4'
io['EXP 00 – ED 05'] = '5'

io['EXP 00 – SD01'] = '6'
io['EXP 00 – SD02'] = '7'
io['EXP 00 – SD03'] = '8'
io['EXP 00 – SD04'] = '9'
io['EXP 00 – SD05'] = '10'

io['EXP 00 – EA 01 DIG'] = '11'
io['EXP 00 – EA 02 DIG'] = '12'
io['EXP 00 – EA 03 DIG'] = '13'
io['EXP 00 – EA 04 DIG'] = '14'
io['EXP 00 – EA 05 DIG'] = '15'
io['EXP 00 – EA 06 DIG'] = '16'

io['EXP 00 – INTERNO 1'] = '17'
io['EXP 00 – INTERNO 2'] = '18'
io['EXP 00 – INTERNO 3'] = '19'
io['EXP 00 – INTERNO 4'] = '20'
io['EXP 00 – INTERNO 5'] = '21'
io['EXP 00 – INTERNO 6'] = '22'

io['EXP 01 – ED 01'] = '31'
io['EXP 01 – ED 02'] = '32'
io['EXP 01 – ED 03'] = '33'
io['EXP 01 – ED 04'] = '34'
io['EXP 01 – ED 05'] = '35'

io['EXP 01 – SD01'] = '36'
io['EXP 01 – SD02'] = '37'
io['EXP 01 – SD03'] = '38'
io['EXP 01 – SD04'] = '39'
io['EXP 01 – SD05'] = '40'

io['EXP 01 – EA 01 DIG'] = '41'
io['EXP 01 – EA 02 DIG'] = '42'
io['EXP 01 – EA 03 DIG'] = '43'
io['EXP 01 – EA 04 DIG'] = '44'
io['EXP 01 – EA 05 DIG'] = '45'
io['EXP 01 – EA 06 DIG'] = '46'

io['EXP 01 – INTERNO 1'] = '47'
io['EXP 01 – INTERNO 2'] = '48'
io['EXP 01 – INTERNO 3'] = '49'
io['EXP 01 – INTERNO 4'] = '50'
io['EXP 01 – INTERNO 5'] = '51'
io['EXP 01 – INTERNO 6'] = '52'

io['EXP 02 – ED 01'] = '61'
io['EXP 02 – ED 02'] = '62'
io['EXP 02 – ED 03'] = '63'
io['EXP 02 – ED 04'] = '64'
io['EXP 02 – ED 05'] = '65'

io['EXP 02 – SD01'] = '66'
io['EXP 02 – SD02'] = '67'
io['EXP 02 – SD03'] = '68'
io['EXP 02 – SD04'] = '69'
io['EXP 02 – SD05'] = '70'

io['EXP 02 – EA 01 DIG'] = '71'
io['EXP 02 – EA 02 DIG'] = '72'
io['EXP 02 – EA 03 DIG'] = '73'
io['EXP 02 – EA 04 DIG'] = '74'
io['EXP 02 – EA 05 DIG'] = '75'
io['EXP 02 – EA 06 DIG'] = '76'

io['EXP 01 – INTERNO 1'] = '47'
io['EXP 01 – INTERNO 2'] = '48'
io['EXP 01 – INTERNO 3'] = '49'
io['EXP 01 – INTERNO 4'] = '50'
io['EXP 01 – INTERNO 5'] = '51'
io['EXP 01 – INTERNO 6'] = '52'

io['EXP 00 – EA 01'] = '1'
io['EXP 00 – EA 02'] = '2'
io['EXP 00 – EA 03'] = '3'
io['EXP 00 – EA 04'] = '4'
io['EXP 00 – EA 05'] = '5'
io['EXP 00 – EA 06'] = '6'

io['EXP 00 – SA 01'] = '7'
io['EXP 00 – SA 02'] = '8'

#io['EXP 00 – INTERNO 1'] = '9'
#io['EXP 00 – INTERNO 2'] = '10'

io['EXP 01 – EA 01'] = '11'
io['EXP 01 – EA 02'] = '12'
io['EXP 01 – EA 03'] = '13'
io['EXP 01 – EA 04'] = '14'
io['EXP 01 – EA 05'] = '15'
io['EXP 01 – EA 06'] = '16'

io['EXP 01 – SA 01'] = '17'
io['EXP 01 – SA 02'] = '18'

#io['EXP 01 – INTERNO 1'] = '19'
#io['EXP 01 – INTERNO 2'] = '20'

io['EXP 02 – EA 01'] = '21'
io['EXP 02 – EA 02'] = '22'
io['EXP 02 – EA 03'] = '23'
io['EXP 02 – EA 04'] = '24'
io['EXP 02 – EA 05'] = '25'
io['EXP 02 – EA 06'] = '26'

io['EXP 02 – SA 01'] = '27'
io['EXP 02 – SA 02'] = '28'

#io['EXP 02 – INTERNO 1'] = '9'
#io['EXP 02 – INTERNO 2'] = '30'

descricao = {}
descricao['CHAVE SELETORA'] = 'entradas.chaveSeletora.pointIndex = '
descricao['STATUS DE LIGADO'] = 'entradas.statusLigado.pointIndex = '
descricao['DEFEITO'] = 'entradas.statusDefeito.pointIndex = '
descricao['TERMOSTATO DE SEGURANÇA'] = 'entradas.termostatoSeguranca.pointIndex = -'
descricao['NÍVEL UMIDIFICADOR'] = 'entradas.nivelUmidificador.pointIndex = -'
descricao['FALTA DE FASE'] = 'entradas.faltaDeFase.pointIndex = -'
descricao['INCÊNDIO'] = 'entradas.incendio.pointIndex = -'
descricao['PROGRAMAÇÃO HORÁRIA'] = 'entradas.hailitacaoProgamacaoHoraria.pointIndex = '
descricao['HABILITAÇÃO DO CONTROLE'] = 'entradas.habilitacaoControle.pointIndex = '
descricao['BLOQUEIO'] = 'entradas.bloqueio.pointIndex = '
descricao['SENSOR'] = 'entradas.sensor.pointIndex = '
descricao['SENSOR DE TEMPERATURA '] = 'entradas.sensorTemperatura.pointIndex = '
descricao['SENSOR DE UMIDADE'] = 'entradas.sensorUmidade.pointIndex = '
descricao['ENTRADA DIGITAL 01'] = 'entradas.ed01.pointIndex = '
descricao['ENTRADA DIGITAL 02'] = 'entradas.ed02.pointIndex = '
descricao['ENTRADA DIGITAL 03'] = 'entradas.ed03.pointIndex = '
descricao['ENTRADA DIGITAL 04'] = 'entradas.ed04.pointIndex = '
descricao['ENTRADA DIGITAL 05'] = 'entradas.ed05.pointIndex = '
descricao['ENTRADA DIGITAL 06'] = 'entradas.ed06.pointIndex = '
descricao['ENTRADA DIGITAL 07'] = 'entradas.ed07.pointIndex = '
descricao['ENTRADA DIGITAL 08'] = 'entradas.ed08.pointIndex = '
descricao['SENSOR 01'] = 'entradas.sensor01.pointIndex = '
descricao['SENSOR 02'] = 'entradas.sensor02.pointIndex = '
descricao['SENSOR 03'] = 'entradas.sensor03.pointIndex = '
descricao['SENSOR 04'] = 'entradas.sensor04.pointIndex = '
descricao['SENSOR 05'] = 'entradas.sensor05.pointIndex = '
descricao['SENSOR 06'] = 'entradas.sensor06.pointIndex = '
descricao['SENSOR 07'] = 'entradas.sensor07.pointIndex = '
descricao['SENSOR 08'] = 'entradas.sensor08.pointIndex = '
descricao['SENSOR 09'] = 'entradas.sensor09.pointIndex = '
descricao['SENSOR 10'] = 'entradas.sensor10.pointIndex = '
descricao['SENSOR 11'] = 'entradas.sensor11.pointIndex = '
descricao['SENSOR 12'] = 'entradas.sensor12.pointIndex = '
descricao['SENSOR 13'] = 'entradas.sensor13.pointIndex = '
descricao['SENSOR 14'] = 'entradas.sensor14.pointIndex = '
descricao['STATUS FILTRO GROSSO INSUFLAMENTO'] = 'entradas.stsFiltroGrossoIns.pointIndex = '
descricao['STATUS FILTRO GROSSO EXAUSTÃO'] = 'entradas.stsFiltroGrossoExt.pointIndex = '
descricao['STATUS DE PORTA'] = 'entradas.stsPorta.pointIndex = '
descricao['PRESSÃO FILTRO FINO INSUFLAMENTO'] = 'entradas.snsPressaoFiltroFinoIns.pointIndex = '
descricao['PRESSÃO FILTRO FINO EXAUSTOR'] = 'entradas.snsPressaoFiltroFinoExt.pointIndex = '
descricao['PRESSÃO FILTRO ABS INSUFLAMENTO'] = 'entradas.snsPressaoFiltroAbsoluto.pointIndex = '
descricao['MONITORAÇÃO CO2'] = 'entradas.snsCO2.pointIndex = '
descricao['PRESSÃO NO DUTO DE EXAUSTÃO'] = 'entradas.snsPressaoExt.pointIndex = '
descricao['TEMPERATURA DE INSUFLAMENTO'] = 'entradas.snsTemperaturaIns.pointIndex = '
descricao['TEMPERATURA DE ALIMENTAÇÃO DE AG'] = 'entradas.snsTemperaturaAAG.pointIndex = '
descricao['TEMPERATURA DE RETORNO DE AG'] = 'entradas.snsTemperaturaRAG.pointIndex = '
descricao['PROPORCIONAL'] = 'saidas.proporcional.pointIndex = '
descricao['ON OFF'] = 'saidas.onOff.pointIndex = '
descricao['STEP 01'] = 'saidas.step.stage01PointIndex = '
descricao['STEP 02'] = 'saidas.step.stage02PointIndex = '
descricao['STEP 03'] = 'saidas.step.stage03PointIndex = '
descricao['STEP 04'] = 'saidas.step.stage04PointIndex = '
descricao['STEP 05'] = 'saidas.step.stage05PointIndex = '
descricao['BLOQUEIO'] = 'saidas.bloqueio.pointIndex = '

pasta = {}
pasta['POINT INDEX – VENTILADOR DE INSUFLAMENTO'] = 'ventiladorInsuflamento.'
pasta['POINT INDEX – EXAUSTOR'] = 'ventiladorExaustao.'
pasta['POINT INDEX – AQUECEDOR'] = 'resistencia.'
pasta['POINT INDEX – UMIDIFICADOR'] = 'umidificador.'
pasta['POINT INDEX – VAG'] = 'valvulaAG.'
pasta['POINT INDEX – MONITORAÇÕES'] = 'monitoracao.'
